### ISSUE TITLE
The FRONTBUFFER_LOCKING variable usage

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#41]
@net147 
The variable  FRONTBUFFER_LOCKING=1 is causing Qt5 Quick application to periodically show black areas with console messages through Quick controls. Then Qt5 renderer immediately redraws those areas. And again.
Can you explain the meaning of variable and when it should be used, please ?

**Comment by net147** [comment]
@sergey-suloev I don't have any explanation of the variable. I only found it by grepping through strings in the Mali fbdev library. You will need to contact ARM if you want an explanation of the variable.
Your problem sounds like a configuration issue with the Linux console writing to the same framebuffer device as Mali.

**Comment by sergey-suloev** [comment]
@net147 Hi, of course it is writing to the same fb device because it is the only device in my system. How can it be different ? By "configuration issue with the Linux console" do you mean  I simply need to disable console output when my Qt5 app is running ?

**Comment by net147** [comment]
@sergey-suloev For many embedded devices you run a graphical application on the graphical display and shell access only using serial port or network. To avoid interference from Linux console, you can add vt.global_cursor_default=0 console=ttyS0 logo.nologo=1 to kernel command line and disable getty from running on tty1 so that nothing is printed to the graphical display when the system is starting up or running that can interfere with your graphical application.

**Comment by sergey-suloev** [comment]
@net147 thanks a lot for sharing this!
